apiVersion: "auth.casbin.org/v1"
kind: UniversalPolicy
metadata:
  name: container-resource-ratio-policy1
  namespace: kubesphere-authz-system
  labels:
    model: container-resource-ratio
spec:
  policyItem: |
    p, default, 2, 2, allow
  

  