# permissions for end users to view universalpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: universalpolicy-viewer-role
rules:
- apiGroups:
  - auth.casbin.org
  resources:
  - universalpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.casbin.org
  resources:
  - universalpolicies/status
  verbs:
  - get
