# permissions for end users to edit universalpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: universalpolicy-editor-role
rules:
- apiGroups:
  - auth.casbin.org
  resources:
  - universalpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.casbin.org
  resources:
  - universalpolicies/status
  verbs:
  - get
